openapi: 3.0.0
info:
  title: DevCamper API
  description: Server-Side API for the DevCamper Application
  version: 1.0.0

servers:
  - url: http://localhost:5000/api/v1
    description: Development server
  - url: https://cheats/kaj.lund.com/api/v1
    description: Production Server

paths:
  /auth/login:
    post:
      summary: Login user
      description: Login usin email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200': #status code
          description: Success Response
          content:
            application/json:
              shema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
        '401':
          description: Failure Response
          content:
            application/json:
              shema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    error: string
